#ifndef __ATOM_TOOLS_MISC_H
#define __ATOM_TOOLS_MISC_H

#define DEVICESTATE_REDNERTARGET	(1<<0)
#define DEVICESTATE_VIEWPORT		(1<<1)
#define DEVICESTATE_CLEARVALUE		(1<<2)
#define DEVICESTATE_TRANSFORM		(1<<3)
#define DEVICESTATE_ALL				(DEVICESTATE_REDNERTARGET|DEVICESTATE_VIEWPORT|DEVICESTATE_CLEARVALUE|DEVICESTATE_TRANSFORM)

void pushDeviceStates (unsigned stateFlags = DEVICESTATE_ALL);
void popDeviceStates (void);

#endif // __ATOM_TOOLS_MISC_H
