#ifndef __ATOM_UTILS_CONFIG_H
#define __ATOM_UTILS_CONFIG_H

#undef ATOM_COMPILER_NO_ARRAYTYPE_SPEC
#define ATOM_COMPILER_HAS_LONG_LONG
#define ATOM_COMPILER_HAS_MS_INT64
#undef ATOM_COMPILER_HAS_QUALIFIERS_ON_REFERENCE

#endif // __ATOM_UTILS_CONFIG_H
